# Generated by Django 5.0.1 on 2024-01-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs.azs')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs_fuel.fuel')),
            ],
        ),
    ]
