# Generated by Django 5.0.1 on 2024-01-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0001_initial'),
        ('azs_fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AZSFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs.azs')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs_fuel.fuel')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
