# Generated by Django 5.0.1 on 2024-01-30 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs.azs')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azs.service')),
            ],
        ),
    ]
