# Generated by Django 5.0.1 on 2024-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0002_service_additionalservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
