# Generated by Django 5.0.1 on 2024-01-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0003_remove_service_status_additionalservices_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalServices',
            new_name='Additional',
        ),
    ]
