# Generated by Django 5.0.1 on 2024-01-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0004_rename_additionalservices_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AZSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Additional',
            new_name='AZSService',
        ),
    ]
