# Generated by Django 5.0.1 on 2024-01-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0005_azsimage_image_rename_additional_azsservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='azsimage',
            name='azs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='azs.azs'),
        ),
        migrations.AddField(
            model_name='azsimage',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='azs.image'),
        ),
        migrations.AlterField(
            model_name='azsimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
